import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'

const SUPABASE_URL='https://peddeglhhwtgqoftcgcx.supabase.co', SUPABASE_ANON_KEY='sb_publishable_KslKm3Zp-M1yr58mw2Xd4Q_hX6VBc9h', ADMIN_WHATSAPP='628000000000'
const supabase=SUPABASE_URL.startsWith('PASTE_')?null:createClient(SUPABASE_URL,SUPABASE_ANON_KEY)
// Tambahkan, ubah, atau hapus kode voucher di sini.
const VOUCHERS={PURBA10:{type:'percent',value:10,label:'Diskon 10%'},HEMAT25:{type:'fixed',value:25000,label:'Potongan Rp25.000',min:150000},CAMP15:{type:'percent',value:15,label:'Diskon 15%',min:250000}}
const $=s=>document.querySelector(s), rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n)
const authModal=$('#auth-modal'),cartModal=$('#cart-modal'),accountModal=$('#account-modal'),authForm=$('#auth-form'),message=$('#form-message'),submit=$('#submit-auth')
let isSignup=false,activeVoucher=null,cart=JSON.parse(localStorage.getItem('purbakala-cart')||'[]')
function toast(text){const e=$('#toast');e.textContent=text;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3000)}
function openAuth(){authModal.classList.add('show')} function closeAuth(){authModal.classList.remove('show');message.textContent=''} function openCart(){renderCart();cartModal.classList.add('show')} function closeCart(){cartModal.classList.remove('show')} async function openAccount(){if(!supabase)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:profile}=await supabase.from('profiles').select('full_name,username,phone').eq('id',user.id).maybeSingle();$('#account-name').value=profile?.full_name||user.user_metadata.full_name||'';$('#account-username').value=profile?.username||user.user_metadata.username||'';$('#account-phone').value=profile?.phone||user.user_metadata.phone||'';$('#account-email').value=user.email||'';$('#account-password').value='';$('#account-message').textContent='';accountModal.classList.add('show')} function closeAccount(){accountModal.classList.remove('show')}
function saveCart(){localStorage.setItem('purbakala-cart',JSON.stringify(cart));$('#cart-count').textContent=cart.reduce((n,x)=>n+x.qty,0)}
function subtotal(){return cart.reduce((n,x)=>n+x.price*x.qty*x.days,0)}
function discount(total){const v=VOUCHERS[activeVoucher];if(!v)return 0;return v.type==='percent'?Math.floor(total*v.value/100):v.value}
function renderCart(){const box=$('#cart-items'),sub=subtotal(),off=discount(sub);box.innerHTML=!cart.length?'<p class="empty-cart">Keranjang masih kosong. Tambahkan perlengkapan yang Anda perlukan.</p>':cart.map((x,i)=>{const isTrip=x.type==='trip',label=isTrip?'peserta':'unit',duration=isTrip?'<small>Harga paket / peserta</small>':`<small>${rupiah(x.price)} / hari</small>`,days=isTrip?'':`<label>Hari<input data-i="${i}" data-f="days" type="number" min="1" value="${x.days}"></label>`;return `<div class="cart-row"><div><strong>${x.name}</strong>${duration}</div><div class="calculator"><label>${isTrip?'Peserta':'Unit'}<input data-i="${i}" data-f="qty" type="number" min="1" value="${x.qty}"></label>${days}</div><div class="subtotal">${rupiah(x.price*x.qty*x.days)}<button data-remove="${i}">Hapus</button></div></div>`}).join('');$('#cart-subtotal').textContent=rupiah(sub);$('#discount-total').textContent='- '+rupiah(off);$('#cart-total').textContent=rupiah(Math.max(0,sub-off));box.querySelectorAll('input').forEach(e=>e.oninput=()=>{cart[e.dataset.i][e.dataset.f]=Math.max(1,Number(e.value)||1);saveCart();renderCart()});box.querySelectorAll('[data-remove]').forEach(e=>e.onclick=()=>{cart.splice(e.dataset.remove,1);saveCart();renderCart()})}
$('#open-auth').onclick=openAuth;$('#close-auth').onclick=closeAuth;$('#cart-button').onclick=openCart;$('#close-cart').onclick=closeCart;$('#account-button').onclick=openAccount;$('#close-account').onclick=closeAccount;authModal.onclick=e=>{if(e.target===authModal)closeAuth()};cartModal.onclick=e=>{if(e.target===cartModal)closeCart()};accountModal.onclick=e=>{if(e.target===accountModal)closeAccount()}
$('#toggle-auth').onclick=()=>{isSignup=!isSignup;document.querySelectorAll('.signup-only').forEach(e=>{e.hidden=!isSignup;e.querySelectorAll('input,select,textarea').forEach(input=>input.required=isSignup)});$('#auth-title').textContent=isSignup?'Buat akun':'Selamat datang';$('#auth-note').textContent=isSignup?'Lengkapi identitas untuk membuat akun Purbakala.':'Masuk untuk melanjutkan pemesanan item.';submit.textContent=isSignup?'Daftar':'Masuk';$('#toggle-auth').textContent=isSignup?'Sudah punya akun? Masuk':'Belum punya akun? Daftar';message.textContent=''}
document.querySelectorAll('.choose').forEach(b=>b.onclick=async()=>{if(!supabase){openAuth();message.textContent='Isi SUPABASE_URL dan SUPABASE_ANON_KEY di app.js terlebih dahulu.';return}const{data:{user}}=await supabase.auth.getUser();if(!user){openAuth();toast('Silakan masuk terlebih dahulu untuk memesan item.');return}const x=cart.find(x=>x.name===b.dataset.item);if(x)x.qty++;else cart.push({name:b.dataset.item,price:Number(b.dataset.price),qty:1,days:1});saveCart();toast(`${b.dataset.item} ditambahkan ke keranjang.`)})
document.querySelectorAll('.trip-join').forEach(b=>b.onclick=async()=>{if(!supabase){openAuth();message.textContent='Isi SUPABASE_URL dan SUPABASE_ANON_KEY di app.js terlebih dahulu.';return}const{data:{user}}=await supabase.auth.getUser();if(!user){openAuth();toast('Silakan masuk terlebih dahulu untuk daftar Open Trip.');return}const name=b.dataset.trip,existing=cart.find(x=>x.name===name);if(existing)existing.qty++;else cart.push({name,price:Number(b.dataset.tripPrice),qty:1,days:1,type:'trip'});saveCart();toast('Open Trip ditambahkan ke keranjang. Lengkapi data diri saat checkout.')})
$('#apply-voucher').onclick=()=>{const code=$('#voucher-code').value.trim().toUpperCase(),v=VOUCHERS[code],note=$('#voucher-message');if(!v){activeVoucher=null;note.textContent='Kode voucher tidak ditemukan.';note.className='error';renderCart();return}if(v.min&&subtotal()<v.min){activeVoucher=null;note.textContent=`Minimal transaksi ${rupiah(v.min)}.`;note.className='error';renderCart();return}activeVoucher=code;note.textContent=`${code} aktif — ${v.label}.`;note.className='success';renderCart()}
$('#renter-form').onsubmit=async e=>{e.preventDefault();if(!cart.length)return toast('Keranjang Anda masih kosong.');if(!supabase){closeCart();openAuth();message.textContent='Isi SUPABASE_URL dan SUPABASE_ANON_KEY di app.js terlebih dahulu.';return}const{data:{user}}=await supabase.auth.getUser();if(!user){closeCart();openAuth();toast('Silakan masuk sebelum checkout.');return}const sub=subtotal(),off=discount(sub),total=Math.max(0,sub-off),lines=cart.map((x,i)=>`${i+1}. ${x.name} — ${x.qty} unit × ${x.days} hari = ${rupiah(x.price*x.qty*x.days)}`).join('\n'),name=$('#renter-name').value,phone=$('#renter-phone').value,idType=$('#identity-type').value,id=$('#identity-number').value,address=$('#renter-address').value,guarantee=$('#guarantee').value,voucher=activeVoucher?`\nVoucher: ${activeVoucher} (-${rupiah(off)})`:'';const text=`Halo Admin Purbakala, saya ingin checkout sewa.\n\nDATA PENYEWA\nNama: ${name}\nWhatsApp: ${phone}\nEmail akun: ${user.email}\n${idType}: ${id}\nAlamat: ${address}\nJaminan: ${guarantee}\n\nITEM SEWA\n${lines}\n\nSubtotal: ${rupiah(sub)}${voucher}\nTotal estimasi: ${rupiah(total)}\nTanggal sewa: (isi tanggal)`;window.open(`https://wa.me/${ADMIN_WHATSAPP}?text=${encodeURIComponent(text)}`,'_blank','noopener')}
$('#account-form').onsubmit=async e=>{e.preventDefault();if(!supabase)return;const note=$('#account-message'),name=$('#account-name').value.trim(),username=$('#account-username').value.trim().replace(/\s+/g,''),phone=$('#account-phone').value.trim(),email=$('#account-email').value.trim(),password=$('#account-password').value;note.textContent='Menyimpan...';note.className='';const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{error:profileError}=await supabase.from('profiles').update({full_name:name,username,phone,email}).eq('id',user.id);if(profileError){note.textContent=profileError.message.includes('unique')?'Username sudah dipakai. Silakan gunakan username lain.':profileError.message;return}const changes={data:{full_name:name,username,phone}};if(email!==user.email)changes.email=email;if(password)changes.password=password;const{error}=await supabase.auth.updateUser(changes);if(error){note.textContent=error.message;return}note.textContent=email!==user.email?'Data disimpan. Konfirmasi email baru yang dikirim Supabase.':'Data akun berhasil disimpan.';note.className='success';$('#account-password').value=''}
async function refreshUser(){if(!supabase)return;const{data:{user}}=await supabase.auth.getUser();if(user){const{data:profile}=await supabase.from('profiles').select('username,full_name').eq('id',user.id).maybeSingle();const username=profile?.username||user.user_metadata.username||profile?.full_name||user.email.split('@')[0];$('#user-greeting').textContent=`Hello, ${username}`;$('#user-greeting').hidden=false;$('#account-button').hidden=false;$('#open-auth').textContent='Keluar';$('#open-auth').onclick=async()=>{await supabase.auth.signOut();location.reload()}}}
authForm.onsubmit=async e=>{e.preventDefault();if(!supabase){message.textContent='Isi SUPABASE_URL dan SUPABASE_ANON_KEY di app.js terlebih dahulu.';return}submit.disabled=true;const meta={full_name:$('#signup-name')?.value.trim(),username:$('#signup-username')?.value.trim().replace(/\s+/g,''),phone:$('#signup-phone')?.value.trim(),birth_date:$('#signup-birthdate')?.value,identity_type:$('#signup-id-type')?.value,identity_number:$('#signup-id-number')?.value.trim(),address:$('#signup-address')?.value.trim()};const r=isSignup?await supabase.auth.signUp({email:$('#email').value,password:$('#password').value,options:{emailRedirectTo:location.origin,data:meta}}):await supabase.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});submit.disabled=false;if(r.error){message.textContent=r.error.message;return}if(isSignup){message.textContent='Akun dibuat. Cek email untuk konfirmasi.';return}closeAuth();toast('Berhasil masuk.');refreshUser()}
// Fitur operasional: tanggal sewa, invoice, riwayat user, dan panel admin.
const addressLabel=$('#renter-address').closest('label');
addressLabel.insertAdjacentHTML('beforebegin','<div class="form-grid rental-dates"><label>Tanggal sewa<input id="rental-start" type="date" required></label><label>Tanggal kembali<input id="rental-end" type="date" required></label></div>');
const orderLines=()=>cart.map((x,i)=>`${i+1}. ${x.name} — ${x.qty} ${x.type==='trip'?'peserta':'unit'} = ${rupiah(x.price*x.qty*x.days)}`).join('\n');
async function loadHistory(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data,error}=await supabase.from('orders').select('invoice_no,status,total,rental_start,rental_end,created_at').eq('user_id',user.id).order('created_at',{ascending:false});const box=$('#history-list');if(error){box.innerHTML='<p>Jalankan file orders-migration.sql di Supabase terlebih dahulu.</p>';return}box.innerHTML=data.length?data.map(o=>`<div class="order-card"><strong>${o.invoice_no}</strong><span class="order-status">${o.status}</span><small>${o.rental_start} s/d ${o.rental_end}</small><b>${rupiah(o.total)}</b></div>`).join(''):'<p>Belum ada pesanan.</p>'}
async function loadAdmin(){const{data,error}=await supabase.from('orders').select('id,invoice_no,status,total,renter_name,renter_phone,rental_start,rental_end,created_at').order('created_at',{ascending:false});const box=$('#admin-list');if(error){box.innerHTML='<p>Anda bukan admin atau migration belum dijalankan.</p>';return}box.innerHTML=data.length?data.map(o=>`<div class="order-card"><strong>${o.invoice_no} — ${o.renter_name}</strong><small>${o.renter_phone} · ${o.rental_start} s/d ${o.rental_end}</small><b>${rupiah(o.total)}</b><select data-status="${o.id}">${['menunggu','dibayar','diproses','disewa','selesai','dibatalkan','dikembalikan'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></div>`).join(''):'<p>Belum ada pesanan.</p>';box.querySelectorAll('[data-status]').forEach(s=>s.onchange=async()=>{await supabase.from('orders').update({status:s.value}).eq('id',s.dataset.status);toast('Status pesanan diperbarui.')})}
$('#history-button').onclick=async()=>{await loadHistory();$('#history-modal').classList.add('show')};$('#close-history').onclick=()=>$('#history-modal').classList.remove('show');$('#history-modal').onclick=e=>{if(e.target===$('#history-modal'))$('#history-modal').classList.remove('show')};$('#admin-button').onclick=async()=>{await loadAdmin();$('#admin-modal').classList.add('show')};$('#close-admin').onclick=()=>$('#admin-modal').classList.remove('show');
$('#renter-form').onsubmit=async e=>{e.preventDefault();if(!cart.length)return toast('Keranjang Anda masih kosong.');if(!supabase){closeCart();openAuth();message.textContent='Isi SUPABASE_URL dan SUPABASE_ANON_KEY di app.js terlebih dahulu.';return}const{data:{user}}=await supabase.auth.getUser();if(!user){closeCart();openAuth();toast('Silakan masuk sebelum checkout.');return}const start=$('#rental-start').value,end=$('#rental-end').value;if(end<start){toast('Tanggal kembali harus setelah tanggal sewa.');return}const sub=subtotal(),off=discount(sub),total=Math.max(0,sub-off),payload={user_id:user.id,rental_start:start,rental_end:end,renter_name:$('#renter-name').value,renter_phone:$('#renter-phone').value,identity_type:$('#identity-type').value,identity_number:$('#identity-number').value,address:$('#renter-address').value,guarantee:$('#guarantee').value,items:cart,subtotal:sub,discount:off,total,voucher_code:activeVoucher};const{data:order,error}=await supabase.from('orders').insert(payload).select('invoice_no').single();if(error){toast('Order belum tersimpan. Jalankan orders-migration.sql di Supabase.');return}const text=`Halo Admin Purbakala, pesanan baru.\n\nInvoice: ${order.invoice_no}\nNama: ${payload.renter_name}\n${orderLines()}\n\nTotal: ${rupiah(total)}\nSewa: ${start} s/d ${end}`;window.open(`https://wa.me/${ADMIN_WHATSAPP}?text=${encodeURIComponent(text)}`,'_blank','noopener');cart=[];activeVoucher=null;saveCart();renderCart();closeCart();toast(`Pesanan ${order.invoice_no} berhasil dibuat.`)};
const previousRefresh=refreshUser;refreshUser=async()=>{await previousRefresh();if(!supabase)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;$('#history-button').hidden=false;const{data:profile}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();if(profile?.role==='admin')$('#admin-button').hidden=false};
saveCart();refreshUser()

// Rating website tersimpan langsung ke Supabase.
let selectedRating=0;
const ratingButtons=[...document.querySelectorAll('#rating-input button')];
function paintStars(){ratingButtons.forEach(b=>b.classList.toggle('active',Number(b.dataset.score)<=selectedRating))}
ratingButtons.forEach(b=>b.onclick=()=>{selectedRating=Number(b.dataset.score);paintStars()});
async function loadReviews(){if(!supabase)return;const{data,error}=await supabase.from('website_reviews').select('display_name,score,comment,created_at').order('updated_at',{ascending:false}).limit(6);const list=$('#reviews-list');if(error){list.innerHTML='<p class="review-card">Ulasan akan aktif setelah ratings-migration.sql dijalankan.</p>';return}const total=data.length,average=total?data.reduce((n,r)=>n+r.score,0)/total:0;$('#rating-average').textContent=total?average.toFixed(1):'–';$('#rating-stars').textContent=total?'★'.repeat(Math.round(average))+'☆'.repeat(5-Math.round(average)):'★★★★★';$('#rating-count').textContent=total?`${total} ulasan dari pelanggan`:'Belum ada ulasan';list.innerHTML=total?data.map(r=>`<article class="review-card"><header><strong>${r.display_name}</strong><span class="stars">${'★'.repeat(r.score)}${'☆'.repeat(5-r.score)}</span></header><p>${r.comment}</p><small>${new Date(r.created_at).toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'})}</small></article>`).join(''):'<p class="review-card">Jadilah yang pertama membagikan pengalaman bersama Purbakala.</p>'}
$('#submit-review').onclick=async()=>{const note=$('#review-message'),comment=$('#review-comment').value.trim();if(!supabase){note.textContent='Hubungkan Supabase terlebih dahulu.';return}if(!selectedRating){note.textContent='Pilih jumlah bintang terlebih dahulu.';return}if(comment.length<3){note.textContent='Tulis ulasan minimal 3 karakter.';return}const{data:{user}}=await supabase.auth.getUser();if(!user){openAuth();note.textContent='';toast('Silakan masuk terlebih dahulu untuk memberi ulasan.');return}const{data:profile}=await supabase.from('profiles').select('full_name,username').eq('id',user.id).maybeSingle();const displayName=profile?.username||profile?.full_name||user.email.split('@')[0];const{error}=await supabase.from('website_reviews').upsert({user_id:user.id,display_name:displayName,score:selectedRating,comment,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error){note.textContent=error.message.includes('does not exist')?'Jalankan ratings-migration.sql di Supabase.':error.message;return}note.style.color='#28753a';note.textContent='Terima kasih, ulasanmu sudah tersimpan.';await loadReviews()};
loadReviews()
