import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'

const SUPABASE_URL='https://peddeglhhwtgqoftcgcx.supabase.co', SUPABASE_ANON_KEY='sb_publishable_KslKm3Zp-M1yr58mw2Xd4Q_hX6VBc9h', ADMIN_WHATSAPP='628000000000'
const supabase=SUPABASE_URL.startsWith('PASTE_')?null:createClient(SUPABASE_URL,SUPABASE_ANON_KEY)
// Tambahkan, ubah, atau hapus kode voucher di sini.
const VOUCHERS={PURBA10:{type:'percent',value:10,label:'Diskon 10%'},HEMAT25:{type:'fixed',value:25000,label:'Potongan Rp25.000',min:150000},CAMP15:{type:'percent',value:15,label:'Diskon 15%',min:250000}}
const $=s=>document.querySelector(s), rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n)
const authModal=$('#auth-modal'),cartModal=$('#cart-modal'),accountModal=$('#account-modal'),authForm=$('#auth-form'),message=$('#form-message'),submit=$('#submit-auth')
let isSignup=false,activeVoucher=null,cart=JSON.parse(localStorage.getItem('purbakala-cart')||'[]')
function toast(text){const e=$('#toast');e.textContent=text;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3000)}
function openAuth(){authModal.classList.add('show')} function closeAuth(){authModal.classList.remove('show');message.textContent=''} function openCart(){renderCart();cartModal.classList.add('show')} function closeCart(){cartModal.classList.remove('show')} async function openAccount(){if(!supabase)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:profile}=await supabase.from('profiles').select('full_name,username,phone').eq('id',user.id).maybeSingle();$('#account-name').value=profile?.full_name||user.user_metadata.full_name||'';$('#account-username').value=profile?.username||user.user_metadata.username||'';$('#account-phone').value=profile?.phone||user.user_metadata.phone||'';$('#account-email').value=user.email||'';$('#account-password').value='';$('#account-message').textContent='';accountModal.classList.add('show')} function closeAccount(){accountModal.classList.remove('show')}
function saveCart(){localStorage.setItem('purbakala-cart',JSON.stringify(cart));$('#cart-count').textContent=cart.reduce((n,x)=>n+x.qty,0)}
function subtotal(){return cart.reduce((n,x)=>n+x.price*x.qty*x.days,0)}
function discount(total){const v=VOUCHERS[activeVoucher];if(!v)return 0;return v.type==='percent'?Math.floor(total*v.value/100):v.value}
function renderCart(){const box=$('#cart-items'),sub=subtotal(),off=discount(sub);box.innerHTML=!cart.length?'<p class="empty-cart">Keranjang masih kosong. Tambahkan perlengkapan yang Anda perlukan.</p>':cart.map((x,i)=>{const isTrip=x.type==='trip',label=isTrip?'peserta':'unit',duration=isTrip?'<small>Harga paket / peserta</small>':`<small>${rupiah(x.price)} / hari</small>`,days=isTrip?'':`<label>Hari<input data-i="${i}" data-f="days" type="number" min="1" value="${x.days}"></label>`;return `<div class="cart-row"><div><strong>${x.name}</strong>${duration}</div><div class="calculator"><label>${isTrip?'Peserta':'Unit'}<input data-i="${i}" data-f="qty" type="number" min="1" value="${x.qty}"></label>${days}</div><div class="subtotal">${rupiah(x.price*x.qty*x.days)}<button data-remove="${i}">Hapus</button></div></div>`}).join('');$('#cart-subtotal').textContent=rupiah(sub);$('#discount-total').textContent='- '+rupiah(off);$('#cart-total').textContent=rupiah(Math.max(0,sub-off));box.querySelectorAll('input').forEach(e=>e.oninput=()=>{cart[e.dataset.i][e.dataset.f]=Math.max(1,Number(e.value)||1);saveCart();renderCart()});box.querySelectorAll('[data-remove]').forEach(e=>e.onclick=()=>{cart.splice(e.dataset.remove,1);saveCart();renderCart()})}
$('#open-auth').onclick=openAuth;$('#close-auth').onclick=closeAuth;$('#cart-button').onclick=openCart;$('#close-cart').onclick=closeCart;$('#account-button').onclick=openAccount;$('#close-account').onclick=closeAccount;authModal.onclick=e=>{if(e.target===authModal)closeAuth()};cartModal.onclick=e=>{if(e.target===cartModal)closeCart()};accountModal.onclick=e=>{if(e.target===accountModal)closeAccount()}
$('#toggle-auth').onclick=()=>{isSignup=!isSignup;document.querySelectorAll('.signup-only').forEach(e=>{e.hidden=!isSignup;e.querySelectorAll('input,select,textarea').forEach(input=>input.required=isSignup)});$('#auth-title').textContent=isSignup?'Buat akun':'Selamat datang';$('#auth-note').textContent=isSignup?'Lengkapi identitas untuk membuat akun Purbakala.':'Masuk untuk melanjutkan pemesanan item.';submit.textContent=isSignup?'Daftar':'Masuk';$('#toggle-auth').textContent=isSignup?'Sudah punya akun? Masuk':'Belum punya akun? Daftar';message.textContent=''}
document.querySelectorAll('.choose').forEach(b=>b.onclick=async()=>{if(!supabase){openAuth();message.textContent='Isi SUPABASE_URL dan SUPABASE_ANON_KEY di app.js terlebih dahulu.';return}const{data:{user}}=await supabase.auth.getUser();if(!user){openAuth();toast('Silakan masuk terlebih dahulu untuk memesan item.');return}const x=cart.find(x=>x.name===b.dataset.item);if(x)x.qty++;else cart.push({name:b.dataset.item,price:Number(b.dataset.price),qty:1,days:1});saveCart();toast(`${b.dataset.item} ditambahkan ke keranjang.`)})
document.querySelectorAll('.trip-join').forEach(b=>b.onclick=async()=>{if(!supabase){openAuth();message.textContent='Isi SUPABASE_URL dan SUPABASE_ANON_KEY di app.js terlebih dahulu.';return}const{data:{user}}=await supabase.auth.getUser();if(!user){openAuth();toast('Silakan masuk terlebih dahulu untuk daftar Open Trip.');return}const name=b.dataset.trip,existing=cart.find(x=>x.name===name);if(existing)existing.qty++;else cart.push({name,price:Number(b.dataset.tripPrice),qty:1,days:1,type:'trip'});saveCart();toast('Open Trip ditambahkan ke keranjang. Lengkapi data diri saat checkout.')})
$('#apply-voucher').onclick=()=>{const code=$('#voucher-code').value.trim().toUpperCase(),v=VOUCHERS[code],note=$('#voucher-message');if(!v){activeVoucher=null;note.textContent='Kode voucher tidak ditemukan.';note.className='error';renderCart();return}if(v.min&&subtotal()<v.min){activeVoucher=null;note.textContent=`Minimal transaksi ${rupiah(v.min)}.`;note.className='error';renderCart();return}activeVoucher=code;note.textContent=`${code} aktif — ${v.label}.`;note.className='success';renderCart()}
$('#renter-form').onsubmit=async e=>{e.preventDefault();if(!cart.length)return toast('Keranjang Anda masih kosong.');if(!supabase){closeCart();openAuth();message.textContent='Isi SUPABASE_URL dan SUPABASE_ANON_KEY di app.js terlebih dahulu.';return}const{data:{user}}=await supabase.auth.getUser();if(!user){closeCart();openAuth();toast('Silakan masuk sebelum checkout.');return}const sub=subtotal(),off=discount(sub),total=Math.max(0,sub-off),lines=cart.map((x,i)=>`${i+1}. ${x.name} — ${x.qty} unit × ${x.days} hari = ${rupiah(x.price*x.qty*x.days)}`).join('\n'),name=$('#renter-name').value,phone=$('#renter-phone').value,idType=$('#identity-type').value,id=$('#identity-number').value,address=$('#renter-address').value,guarantee=$('#guarantee').value,voucher=activeVoucher?`\nVoucher: ${activeVoucher} (-${rupiah(off)})`:'';const text=`Halo Admin Purbakala, saya ingin checkout sewa.\n\nDATA PENYEWA\nNama: ${name}\nWhatsApp: ${phone}\nEmail akun: ${user.email}\n${idType}: ${id}\nAlamat: ${address}\nJaminan: ${guarantee}\n\nITEM SEWA\n${lines}\n\nSubtotal: ${rupiah(sub)}${voucher}\nTotal estimasi: ${rupiah(total)}\nTanggal sewa: (isi tanggal)`;window.open(`https://wa.me/${ADMIN_WHATSAPP}?text=${encodeURIComponent(text)}`,'_blank','noopener')}
$('#account-form').onsubmit=async e=>{e.preventDefault();if(!supabase)return;const note=$('#account-message'),name=$('#account-name').value.trim(),username=$('#account-username').value.trim().replace(/\s+/g,''),phone=$('#account-phone').value.trim(),email=$('#account-email').value.trim(),password=$('#account-password').value;note.textContent='Menyimpan...';note.className='';const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{error:profileError}=await supabase.from('profiles').update({full_name:name,username,phone,email}).eq('id',user.id);if(profileError){note.textContent=profileError.message.includes('unique')?'Username sudah dipakai. Silakan gunakan username lain.':profileError.message;return}const changes={data:{full_name:name,username,phone}};if(email!==user.email)changes.email=email;if(password)changes.password=password;const{error}=await supabase.auth.updateUser(changes);if(error){note.textContent=error.message;return}note.textContent=email!==user.email?'Data disimpan. Konfirmasi email baru yang dikirim Supabase.':'Data akun berhasil disimpan.';note.className='success';$('#account-password').value=''}
async function refreshUser(){if(!supabase)return;const{data:{user}}=await supabase.auth.getUser();if(user){const{data:profile}=await supabase.from('profiles').select('username,full_name').eq('id',user.id).maybeSingle();const username=profile?.username||user.user_metadata.username||profile?.full_name||user.email.split('@')[0];$('#user-greeting').textContent=`Hello, ${username}`;$('#user-greeting').hidden=false;$('#account-button').hidden=false;$('#open-auth').textContent='Keluar';$('#open-auth').onclick=async()=>{await supabase.auth.signOut();location.reload()}}}
authForm.onsubmit=async e=>{e.preventDefault();if(!supabase){message.textContent='Isi SUPABASE_URL dan SUPABASE_ANON_KEY di app.js terlebih dahulu.';return}submit.disabled=true;const meta={full_name:$('#signup-name')?.value.trim(),username:$('#signup-username')?.value.trim().replace(/\s+/g,''),phone:$('#signup-phone')?.value.trim(),birth_date:$('#signup-birthdate')?.value,identity_type:$('#signup-id-type')?.value,identity_number:$('#signup-id-number')?.value.trim(),address:$('#signup-address')?.value.trim()};const r=isSignup?await supabase.auth.signUp({email:$('#email').value,password:$('#password').value,options:{emailRedirectTo:location.origin,data:meta}}):await supabase.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});submit.disabled=false;if(r.error){message.textContent=r.error.message;return}if(isSignup){message.textContent='Akun dibuat. Cek email untuk konfirmasi.';return}closeAuth();toast('Berhasil masuk.');refreshUser()}
saveCart();refreshUser()
